version: '3'
services:
  db:
    container_name: todo_db
    image:  postgres:11-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todo_db
    expose:
        - "5432"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
